sudo: required

language: python
python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - BUILD_ON_TRAVIS=true
    - IS_HEROKU_TEST=1
  matrix:
    - DJANGO_VERSION=1.11.5 DB=postgresql

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

before_script:
  - psql -c 'create database travis_ci_db;' -U postgres
  - python manage.py makemigrations

script:
  - python manage.py migrate
  - python manage.py test

deploy:
  provider: heroku
  buildpack: python
  api_key:
    secure: 8c6f49c0-f5fc-4271-b731-96d679998743
  strategy: git
  app: checash
  on:
    repo: serafim-end/checash
  run:
    - "python checash/manage.py makemigrations --noinput"
    - "python checash/manage.py migrate"
    - "python checash/manage.py collectstatic"
    - restart