sudo: required

language: python
python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - BUILD_ON_TRAVIS=true
    - IS_HEROKU_TEST=1
  matrix:
    - DJANGO_VERSION=1.11.5 DB=postgresql

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install codecov

before_script:
  - psql -c 'create database travis_ci_db;' -U postgres
  - python manage.py makemigrations

script:
  - python manage.py migrate
  - coverage run tests.py
#  - python manage.py test

after_success:
  - codecov

#deploy:
#  provider: heroku
#  buildpack: heroku/python
#  api_key:
#    secure: 8c6f49c0-f5fc-4271-b731-96d679998743
#  strategy: git
#  app: checash
#  on:
#    repo: heroku/checash
#    branch: master
#  run:
#    - "python checash/manage.py makemigrations --noinput"
#    - "python checash/manage.py migrate"
#    - "python checash/manage.py collectstatic"
#    - restart